[[override]]
  name = "github.com/pulumi/pulumi"
  version = "v0.12.2"

[[override]]
  name = "github.com/pulumi/pulumi-terraform"
  revision = "3c809d5b5a993ede15ff4f393237086582aff855"

[[constraint]]
  name = "github.com/terraform-providers/terraform-provider-azurerm"
  version = "=1.6.0"

[[override]]
  name = "github.com/pulumi/terraform"
  branch = "pulumi-master"
