[tools]
golangci-lint = "2.5.0"
"vfox-pulumi:pulumi/pulumi-random" = "latest"
"vfox-pulumi:pulumi/pulumi-azuread" = "latest"
"vfox-pulumi:pulumiverse/pulumi-time" = "latest"
"vfox-pulumi:pulumi/pulumi-local" = "latest"
"vfox-pulumi:pulumi/pulumi-std" = "latest"
"vfox-pulumi:pulumi/pulumi-converter-terraform" = "latest"